server:
  port: 7000
spring:
  application:
    name: gateway-api
  # Redis服务地址
  redis:
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # session配置
  session:
    timeout: 86400 # 设置session失效时间
    store-type: redis # 修改spring-session存储配置，默认存储到服务器内存中，现在设置存到redis中（关键）

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: buy-service
          uri: lb://buy-service
          order: 0
          predicates:
            - Path=/api/buy/**
        - id: commodity-manage-service
          uri: lb://commodity-manage-service
          order: 0
          predicates:
            - Path=/api/commodity/**
        - id: invoice-manage-service
          uri: lb://invoice-manage-service
          order: 0
          predicates:
            - Path=/api/invoice/**
        - id: login-service            # 路由的唯一标识
          uri: lb://login-service   # 如果断言成功，将要转发去的地址
          order: 0                    # 优先级，越小优先级越高
          predicates: # 断言，满足所有断言，才会进行转发
            - Path=/api/user/**        # 注意：这是使用= 不是：
        - id: order-manage-service
          uri: lb://order-manage-service
          order: 0
          predicates:
            - Path=/api/order/**
        - id: purchaseorder-manage-service
          uri: lb://purchaseorder-manage-service
          order: 0
          predicates:
            - Path=/api/purchaseorder/**
        - id: user-manage-service
          uri: lb://user-manage-service
          order: 0
          predicates:
            - Path=/api/userinfo/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
              -
      # 开启服务发现

