server:
  port: 7000
spring:
  application:
    name: gateway-api
  # Redis服务地址
  redis:
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # session配置
  session:
    timeout: 86400 # 设置session失效时间
    store-type: redis # 修改spring-session存储配置，默认存储到服务器内存中，现在设置存到redis中（关键）

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: buy-service
          uri: lb://buy-service
          order: 0
          predicates:
            - Path=/buy/**
        - id: commodity-manage-service
          uri: lb://commodity-manage-service
          order: 0
          predicates:
            - Path=/commodity/**
        - id: invoice-manage-service
          uri: lb://invoice-manage-service
          order: 0
          predicates:
            - Path=/invoice/**
        - id: login-service            # 路由的唯一标识
          uri: lb://login-service   # 如果断言成功，将要转发去的地址
          order: 0                    # 优先级，越小优先级越高
          predicates: # 断言，满足所有断言，才会进行转发
            - Path=/user/**       # 注意：这是使用= 不是：
        - id: order-manage-service
          uri: lb://order-manage-service
          order: 0
          predicates:
            - Path=/order/**
        - id: purchaseorder-manage-service
          uri: lb://purchaseorder-manage-service
          order: 0
          predicates:
            - Path=/purchaseorder/**
        - id: user-manage-service
          uri: lb://user-manage-service
          order: 0
          predicates:
            - Path=/userinfo/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
      # 开启服务发现
      discovery:
          locator:
            #是否与服务发现组件进行结合，通过serviceId转发到具体实例
            #是否开启基于服务发现的路由规则
           enabled: true
        ##表示将请求路径的服务名配置改成小写 ,因为服务注册的时候，向注册中心注册时将服务名转成大写的了
           lowerCaseServiceId: true
