server:
  port: 7000
spring:
  application:
    name: gateway-api
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      # 网关配置跨域请求
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
      # 开启服务发现
      discovery:
        locator:
          enabled: true   # 通过微服务名称进行路由，实现动态路由和负载均衡

      # 配置网关路线
      routes:
        - id: payment_routh           # 路由的Id，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service  # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/getPaymentById/**    # 断言 路径相匹配的进行路由

        - id: payment_routh2           # 路由的Id，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service   # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/feignTimeout/**    # 断言 路径相匹配的进行路由